spring:
 profiles:
    active:
    - dev
---
spring:
 profiles: dev
 application:
     name: microservicecloud-config-nikoyo-dev
---
spring:
 profiles: test
 application:
     name: microservicecloud-config-nikoyo-test